CC = gcc

all:
	$(CC) lista.c -o lista.o
	$(CC) fila.c -o fila.o
	$(CC) pilha.c -o pilha.o

lista:
	$(CC) lista.c -o lista.o

fila:
	$(CC) fila.c -o fila.o

pilha:
	$(CC) pilha.c -o pilha.o

clean:
	rm -rf *.o